### ISSUE TITLE
Flyweight example improvements

### ISSUE THREAD

**Issue by markmc27** [RobbieLD/patterns#3]
My understanding of Flyweight is that it reuses heavy/expensive objects across multiple other objects. For example, in the bike race scenario, I think a better example of the flyweight pattern would be something like:

Competitor: A competitor has a race number, height, weight, name, and a Bike (abstract class). There will be one type of each Bike instantiated and used across the application via the Flyweight pattern.

Bike has methods like Accelerate, NegotiatePothole, Brake, etc, and properties like TopSpeed and Weight. So you could then interact with any competitor using competitor.Bike.Brake() and the braking speed would be defined by the Bike's weight and brake types.

The one part of this that I can't figure out is how the Bike is then added to the Competitor - maybe the competitor constructor has a Bike parameter? 

You've already covered the immutability of the Flyweight object by using protected for the speed - would readonly be helpful here too?

**Comment by RobbieLD** [comment]
Yeah having it setup but like that probably does make it clearer but the bit that bothers me about having it that way is that because the bikes are reused the example sort of breaks down because because calling competitor.Bike.Brake() will call break on 'all' the bikes of that type (because they are the same object). I think the metaphor of a bike race is probably floored here since in a real race every competitor and their bike is it's own object, for obvious reasons. 

A couple of other ideas of structuring it come to mind though. I like the idea of the race since it's a good example which has a lot of objects but say you have competitors and bikes but say only two or three sponsoring companies. The sponsor class is the bit which can be shared since there really are only a few companies. I can't really think of a good method for the sponsor class to have. Maybe something like `getSlogan` or `getLogo`.

Another idea which solves the problem with the sponsor method is a bike race with lots of competitors but only a few stages. Then each stage is shared among all the competitors depending on which stage of the race they are in. Having them being moved in and out of stages though seems like it's muddying the concept here a little with extra detail that isn't actually part of the pattern.

**Comment by RobbieLD** [comment]
I've had some more thoughts about it and I felt that the whole bike race thing wasn't a good analogy for this pattern so I've written it again. This time it's a bike painting shop. They have a paint robot for each colour they need to paint a bike. This way they only make a new robot when there's a new colour they haven't painted a bike before. I've submitted PR  https://github.com/RobbieLD/patterns/pull/4 so you can see if this one makes more sense.

**Comment by markmc27** [comment]
I like this example with the robots, I think it's a more concrete Flyweight pattern. The other idea I had for the bike race was for each competitor to have a `Charity` - I think that's similar to the Sponsor option you suggested earlier. 

But the robot painting is a much better example, nice work! 🙌 😁

**Comment by RobbieLD** [comment]
Thanks, I'll close the issue now and complete the PR so the refactor can get into master. I've opened a new issue for adding new patterns https://github.com/RobbieLD/patterns/issues/5
